# Change these first
owner: byucsstudent
repo: pizzaupptime

sites:
  - name: JWT Pizza
    url: https://pizza.byucsstudent.click

status-website:
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/byucsstudent/pizzaupptime/master/static/img/icon.svg
  name: JWT Pizza
  introTitle: "**JWTPizza** the finest virtual pizza joint on the planet."
  introMessage: "We make every effort to keep the pizzas flying, but if there is something wrong you will see it reported here"
  navbar:
    - title: Status
      href: https://status.byucsstudent.click
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
