owner: byucsstudent
repo: pizzaupptime

sites:
  - name: JWT Pizza
    url: https://pizza.byucsstudent.click

status-website:
  cname: status.byucsstudent.click
  baseUrl: /
  logoUrl: https://pizza.byucsstudent.click/jwt-pizza-icon.png
  showPoweredBy: false
  name: JWT Pizza
  introTitle: "🍕 **JWT Pizza** - The finest virtual pizza joint on the planet."
  introMessage: "We make every effort to keep the pizzas flying, but if there is something wrong you will see it reported here"
  navbar:
    - title: Pizza
      href: https://pizza.byucsstudent.click
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
